# Generated by Django 3.2.7 on 2021-10-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharebookApp', '0002_auto_20211017_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='sharebookApp.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='sharebookApp.grade'),
        ),
    ]
