# Generated by Django 3.2.8 on 2021-10-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharebookApp', '0004_auto_20211019_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
